backend:
  name: git-gateway
  branch: main

site_url: https://underworld-db.netlify.app
display_url: https://underworld-db.netlify.app

# comment out editorial workflow to reduce API surface while we stabilize login
# publish_mode: editorial_workflow

media_folder: "admin/media"
public_folder: "/admin/media"

# (optional) restrict to Identity roles
# backend roles are managed on Netlify; this just documents intent
