name: Publish DB
on:
  push:
    branches: [ main ]
    paths: [ "cms/**", "tools/pack_cms.py", "build_manifest.py" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow committing/tagging
      actions: write    # allow updating workflows
      # Alternative: use this broader permission instead of the above two
      # workflows: write  # allow modifying workflow files
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch full history to avoid push conflicts
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }

      - name: Pack CMS -> db_src
        run: python tools/pack_cms.py

      - name: Build manifest + versioned bundle
        id: build
        run: |
          ver=$(python build_manifest.py | tail -n1)
          echo "ver=$ver" >> $GITHUB_OUTPUT

      - name: Commit outputs and tag
        run: |
          git config user.name  "db-bot"
          git config user.email "db-bot@users.noreply.github.com"
          
          # Stash any changes, pull latest, then pop stash
          git stash push -m "build artifacts" || true
          git pull origin main --rebase || git pull origin main
          git stash pop || true
          
          # Add and commit the built files
          git add db_src manifest.json cdn
          git commit -m "db ${{ steps.build.outputs.ver }}" || echo "no changes"
          git tag -f "db-${{ steps.build.outputs.ver }}"
          git push origin main --tags

      - name: Purge jsDelivr (optional)
        run: |
          curl -s "https://purge.jsdelivr.net/gh/${{ github.repository }}"
          curl -s "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/manifest.json"
